name: Mise à jour hebdomadaire FREE DOM

on:
  schedule:
    # Exécution tous les lundis à 8h (heure Réunion = 4h UTC)
    - cron: '0 4 * * 1'
  workflow_dispatch:  # Permet l'exécution manuelle

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run update script
        run: python update_data.py

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add data.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Mise à jour hebdomadaire $(date +'%d/%m/%Y')"
          git push